name: Release python package (WIP)

on:
  workflow_dispatch:
    inputs:
      increment:
        description: 'major/minor/patch'
        required: true
        default: 'patch'

jobs:
  release:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Output current version
      run: |
        poetry version
    - name: Try a bump
      run: |
        poetry version ${{ github.event.inputs.increment }}
    - name: Display result
      run: |
        git diff
